[clipboard]
[clipboard.plots]
discrete_isofields = true
integral_isofields = true

summary_spectres_cx = true
summary_spectres_cy = true
summary_spectres_cmz = true

summary_coefficients_cx = true
summary_coefficients_cy = true
summary_coefficients_cmz = true

summary_coefficients_polar = true

envelopes = true

[clipboard.data_from_db]
pressure_coefficients = true
coordinates = true
average_wind_speed = true
face_number = true
cx = true
cy = true
cmz = true

[plots]
dpi = 200  # Качество отрисовки графиков

[core]
count_threads = 10  # Количество запускаемых потоков при создании отчета

[databasetoolkit]
min_count_connections = 10
max_count_connections = 10
time_sleep = 3  # Время между запросами нового подлючения если доступных нет, в секундах