[clipboard]
[clipboard.plots]
pseudocolor_coefficients = false

isofields_pressure = false
isofields_coefficients = false

summary_spectres_cx = false
summary_spectres_cy = false
summary_spectres_cmz = false

summary_coefficients_cx = false
summary_coefficients_cy = false
summary_coefficients_cmz = false
summary_coefficients_polar = false

envelopes = false

model_polar = false
model_3d = false

[clipboard.data_from_db]
pressure_coefficients = true
coordinates = true
average_wind_speed = true
face_number = true
cx = true
cy = true
cmz = true

[clipboard.settings]
read_clipboard_binary = false

[plots]
dpi = 200  # Качество отрисовки графиков

[core]
count_threads = 16  # Количество запускаемых потоков при работе

[databasetoolkit]
min_count_connections = 16
max_count_connections = 16
time_sleep = 1  # Время между запросами нового подлючения если доступных нет, в секундах