class Plot:
    DPI = 50
    TITLE_FONTSIZE = 20
    XTICKS_FONTSIZE = 20
    YTICKS_FONTSIZE = 20
    LEGEND_FONTSIZE = 20
    XLABEL_FONTSIZE = 20
    YLABEL_FONTSIZE = 20
    COLORBAR_FONTSIZE = 15
    PLOT_TEXT_FONTSIZE = 20
