#:include GUI/kv/NavigationBar.kv

#:include GUI/kv/HomeScreen.kv
#:include GUI/kv/IsolatedHighriseScreen.kv
#:include GUI/kv/ReportContent.kv
#:include GUI/kv/InterferenceHighriseScreen.kv
#:include GUI/kv/RoofWithoutEaves.kv
#:include GUI/kv/RoofWithEaves.kv


WindSpectrumScreens:
    HomeScreen:
    IsolatedHighriseScreen:
    InterferenceHighriseScreen:
    RoofWithoutEaves:
    RoofWithEaves:

    ReportContent:
