name: import_linter    # название скрипта: будет отображаться во вкладке Actions

on:
  push:
    branches:
      - '*'

#  pull_request:
#    branches:
#      - '*'
permissions:
#  actions: read|write|none
#  checks: read|write|none
#  contents: read|write|none
#  deployments: read|write|none
#  discussions: read|write|none
#  pages: read|write|none
#  pull-requests: read|write|none
#  repository-projects: write


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/import_linter/requirements.txt
      - name: Give permission
        run: chmod +x .github/workflows/import_linter/import_linter.sh
      - name: Run import-linter
        run: .github/workflows/import_linter/import_linter.sh ./src .github/workflows/import_linter/.isort.cfg

      - name: Configure Git 1
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"

      - name: Commit and push changes
        run: |
          git add .  
          git commit -m "import_linter"
          git push origin HEAD:import_linter  # Пуш в ветку, например, в 'main'