name: import_linter

on:
  pull_request:
    branches:
      - '*'

jobs:
  make_imports_beautiful_again:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/import_linter/requirements.txt

      - name: Stash changes (if any)
        run: |
          git add .
          git stash || echo "No changes to stash"

      - name: Pull latest changes with auto-merge
        run: |
          git fetch origin
          git merge origin/main --allow-unrelated-historie

      - name: Run Import Linter
        run: .github/workflows/import_linter/import_linter.sh ./src .github/workflows/import_linter/.isort.cfg

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated conflict resolution and import linter" || echo "Nothing to commit"
          git push https://${{ secrets.TOKEN_CI_CD }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI_CD }}

