name: import_linter

on:
  pull_request:
    branches:
      - '*'

jobs:
  make_imports_buatifull_again:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/import_linter/requirements.txt

      - name: Give permission
        run: chmod +x .github/workflows/import_linter/import_linter.sh

      - name: Run import-linter
        run: .github/workflows/import_linter/import_linter.sh ./src .github/workflows/import_linter/.isort.cfg

      - name: Configure Git
        run: |
          git config user.name "import_linter bot"
          git config user.email "import_linter@import_linter.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "import linter" || echo "Nothing to commit"
          git push https://${{ secrets.TOKEN_CI_CD }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_CI_CD }}